[2021-09-13 07:21:23,437] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-13 07:21:23,441] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-13 07:21:23,445] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-13 07:21:23,450] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-13 07:21:23,454] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-13 07:21:23,458] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-13 07:21:23,462] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-13 07:21:23,465] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-13 07:21:23,468] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-13 07:21:35,132] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-13 07:21:35,142] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-13 07:21:36,588] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-13 07:21:36,592] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-13 07:21:36,860] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-13 07:30:55,833] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/yolo-test.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/yolo-test.jpg'
[2021-09-13 07:30:56,216] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-09-13 07:30:56,222] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7fd1ef4cfd10>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fd1ef4cfd10>
[2021-09-13 07:32:14,126] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/car.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/car.jpg'
[2021-09-13 07:32:14,139] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-09-13 07:32:14,146] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7fd1f086fb30>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fd1f086fb30>
[2021-09-13 07:42:04,231] [WARNING] __main__ main.py:182 - closing all external connections
[2021-09-13 07:42:04,252] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-09-13 07:42:04,260] [WARNING] __main__ main.py:194 - asyncmain exiting
[2021-09-13 07:42:40,630] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-13 07:42:40,633] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-13 07:42:40,636] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-13 07:42:40,639] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-13 07:42:40,641] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-13 07:42:40,645] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-13 07:42:40,648] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-13 07:42:40,652] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-13 07:42:40,655] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-13 07:42:44,862] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-13 07:42:44,870] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-13 07:42:45,743] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-13 07:42:45,747] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-13 07:42:45,853] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-13 07:42:58,539] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2021-09-13 07:42:58,545] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2021-09-13 07:45:59,318] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-13 07:45:59,326] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-13 07:45:59,332] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-13 07:45:59,338] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-13 07:45:59,344] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-13 07:45:59,351] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-13 07:45:59,356] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-13 07:45:59,360] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-13 07:45:59,367] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-13 07:46:03,330] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-13 07:46:03,337] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-13 07:46:04,429] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-13 07:46:04,432] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-13 07:46:04,583] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-13 07:47:26,476] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-13 07:47:26,480] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-13 07:47:26,485] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-13 07:47:26,490] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-13 07:47:26,495] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-13 07:47:26,500] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-13 07:47:26,505] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-13 07:47:26,511] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-13 07:47:26,517] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-13 07:47:29,464] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-13 07:47:29,472] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-13 07:47:30,211] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-13 07:47:30,215] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-13 07:47:30,314] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-13 07:49:59,175] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-13 07:49:59,178] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-13 07:49:59,182] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-13 07:49:59,186] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-13 07:49:59,190] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-13 07:49:59,193] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-13 07:49:59,197] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-13 07:49:59,201] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-13 07:49:59,205] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-13 07:50:02,074] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-13 07:50:02,080] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-13 07:50:02,819] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-13 07:50:02,822] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-13 07:50:02,917] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-13 07:51:27,040] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2021-09-13 07:51:27,047] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2021-09-13 08:02:46,945] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-13 08:02:46,947] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-13 08:02:46,957] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-13 08:02:46,966] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-13 08:02:46,971] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-13 08:02:46,981] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-13 08:02:46,989] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-13 08:02:47,000] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-13 08:02:47,014] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-13 08:02:50,177] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-13 08:02:50,183] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-13 08:02:51,008] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-13 08:02:51,011] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-13 08:02:51,136] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-13 08:03:10,225] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2021-09-13 08:03:10,229] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2021-09-18 10:19:47,704] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-18 10:19:47,708] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-18 10:19:47,712] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-18 10:19:47,716] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-18 10:19:47,720] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-18 10:19:47,725] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-18 10:19:47,729] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-18 10:19:47,732] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-18 10:19:47,736] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-18 10:20:02,589] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-18 10:20:02,601] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-18 10:20:04,673] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-18 10:20:04,679] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-18 10:20:04,940] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-18 10:31:23,882] [WARNING] __main__ main.py:182 - closing all external connections
[2021-09-18 10:31:23,886] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-09-18 10:31:23,889] [WARNING] __main__ main.py:194 - asyncmain exiting
[2021-09-18 10:37:13,986] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-18 10:37:13,990] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-18 10:37:13,994] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-18 10:37:13,998] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-18 10:37:14,000] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-18 10:37:14,003] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-18 10:37:14,007] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-18 10:37:14,010] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-18 10:37:14,014] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-18 10:37:22,780] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-18 10:37:22,787] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-18 10:37:23,854] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-18 10:37:23,857] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-18 10:37:24,058] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-18 10:41:06,342] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-18 10:41:06,345] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-18 10:41:06,349] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-18 10:41:06,352] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-18 10:41:06,356] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-18 10:41:06,359] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-18 10:41:06,363] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-18 10:41:06,367] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-18 10:41:06,370] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-18 10:41:09,661] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-18 10:41:09,667] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-18 10:41:10,432] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-18 10:41:10,436] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-18 10:41:10,532] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-18 10:44:23,392] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-18 10:44:23,396] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-18 10:44:23,402] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-18 10:44:23,405] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-18 10:44:23,409] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-18 10:44:23,414] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-18 10:44:23,418] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-18 10:44:23,422] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-18 10:44:23,426] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-18 10:44:27,490] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-18 10:44:27,499] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-18 10:44:28,790] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-18 10:44:28,794] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-18 10:44:29,067] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-18 13:53:45,495] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-18 13:53:45,503] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-18 13:53:45,509] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-18 13:53:45,517] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-18 13:53:45,523] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-18 13:53:45,529] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-18 13:53:45,536] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-18 13:53:45,544] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-18 13:53:45,557] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-18 13:53:53,125] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-18 13:53:53,139] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-18 13:53:54,854] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-18 13:53:54,862] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-18 13:53:55,039] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-18 13:54:29,031] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/20d393f65a9807c9.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/20d393f65a9807c9.jpg'
[2021-09-18 13:54:29,371] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-09-18 13:54:29,376] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7f8a11749900>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8a11749900>
[2021-09-18 13:54:29,432] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/ef901640466be2cf.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/ef901640466be2cf.jpg'
[2021-09-18 13:54:29,445] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-09-18 13:54:29,451] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7f8a12aceea0>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8a12aceea0>
[2021-09-18 13:54:29,482] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/6145e7c42529c.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/6145e7c42529c.jpg'
[2021-09-18 13:54:29,499] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-09-18 13:54:29,511] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7f8a1172bb30>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8a1172bb30>
[2021-09-18 14:00:28,562] [WARNING] __main__ main.py:182 - closing all external connections
[2021-09-18 14:00:28,578] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-09-18 14:00:28,583] [WARNING] __main__ main.py:194 - asyncmain exiting
[2021-09-18 14:00:45,720] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-18 14:00:45,723] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-18 14:00:45,728] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-18 14:00:45,733] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-18 14:00:45,738] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-18 14:00:45,744] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-18 14:00:45,751] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-18 14:00:45,757] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-18 14:00:45,763] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-18 14:00:50,297] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-18 14:00:50,306] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-18 14:00:51,353] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-18 14:00:51,358] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-18 14:00:51,470] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-18 14:02:03,596] [WARNING] __main__ main.py:182 - closing all external connections
[2021-09-18 14:02:03,604] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-09-18 14:02:03,609] [WARNING] __main__ main.py:194 - asyncmain exiting
[2021-09-18 14:03:59,967] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-18 14:03:59,975] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-18 14:03:59,982] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-18 14:03:59,994] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-18 14:03:59,998] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-18 14:04:00,005] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-18 14:04:00,011] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-18 14:04:00,017] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-18 14:04:00,023] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-18 14:04:05,162] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-18 14:04:05,176] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-18 14:04:06,648] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-18 14:04:06,653] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-18 14:04:06,810] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-18 14:11:26,933] [WARNING] __main__ main.py:182 - closing all external connections
[2021-09-18 14:11:26,957] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-09-18 14:11:26,993] [WARNING] __main__ main.py:194 - asyncmain exiting
[2021-09-18 14:19:47,697] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-18 14:19:47,703] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-18 14:19:47,710] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-18 14:19:47,717] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-18 14:19:47,724] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-18 14:19:47,730] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-18 14:19:47,735] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-18 14:19:47,744] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-18 14:19:47,751] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-18 14:19:55,194] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-18 14:19:55,213] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-18 14:19:57,055] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-18 14:19:57,066] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-18 14:19:57,403] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-18 14:29:15,756] [WARNING] __main__ main.py:182 - closing all external connections
[2021-09-18 14:29:15,764] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-09-18 14:29:15,773] [WARNING] __main__ main.py:194 - asyncmain exiting
[2021-09-19 01:35:01,591] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-19 01:35:01,595] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-19 01:35:01,600] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-19 01:35:01,605] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-19 01:35:01,610] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-19 01:35:01,616] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-19 01:35:01,622] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-19 01:35:01,629] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-19 01:35:01,635] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-19 01:35:16,062] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-19 01:35:16,076] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-19 01:35:18,401] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-19 01:35:18,414] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-19 01:35:18,668] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-10-28 06:16:52,173] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-10-28 06:16:52,178] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-10-28 06:16:52,182] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-10-28 06:16:52,186] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-10-28 06:16:52,189] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-10-28 06:16:52,193] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-10-28 06:16:52,196] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-10-28 06:16:52,201] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-10-28 06:16:52,205] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-10-28 06:17:06,582] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-10-28 06:17:06,604] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-10-28 06:17:10,340] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-10-28 06:17:10,346] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-10-28 06:17:10,586] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-10-28 06:26:36,873] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/car.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/car.jpg'
[2021-10-28 06:26:37,058] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-10-28 06:26:37,063] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7fa40f6cc680>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa40f6cc680>
[2021-10-28 06:26:59,810] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/car.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/car.jpg'
[2021-10-28 06:26:59,817] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-10-28 06:26:59,820] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7fa40f8263b0>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa40f8263b0>
[2021-10-28 06:27:09,526] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/car.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/car.jpg'
[2021-10-28 06:27:09,537] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2021-10-28 06:27:09,542] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7fa40f6cc4a0>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa40f6cc4a0>
[2021-10-28 06:29:10,038] [WARNING] __main__ main.py:182 - closing all external connections
[2021-10-28 06:29:10,046] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-10-28 06:29:10,049] [WARNING] __main__ main.py:194 - asyncmain exiting
[2021-10-28 07:04:31,006] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-10-28 07:04:31,011] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-10-28 07:04:31,015] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-10-28 07:04:31,019] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-10-28 07:04:31,023] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-10-28 07:04:31,027] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-10-28 07:04:31,032] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-10-28 07:04:31,036] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-10-28 07:04:31,041] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-10-28 07:04:35,696] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-10-28 07:04:35,705] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-10-28 07:04:36,833] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-10-28 07:04:36,839] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-10-28 07:04:36,967] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-04 13:21:39,399] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2022-03-04 13:21:39,403] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2022-03-04 13:21:39,406] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2022-03-04 13:21:39,410] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2022-03-04 13:21:39,422] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2022-03-04 13:21:39,426] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2022-03-04 13:21:39,430] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2022-03-04 13:21:39,433] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2022-03-04 13:21:39,439] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2022-03-04 13:21:49,632] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2022-03-04 13:21:49,642] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2022-03-04 13:21:50,792] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2022-03-04 13:21:50,795] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2022-03-04 13:21:51,021] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-04 13:26:54,129] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2022-03-04 13:26:54,132] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2022-03-04 13:26:54,135] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2022-03-04 13:26:54,138] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2022-03-04 13:26:54,142] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2022-03-04 13:26:54,146] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2022-03-04 13:26:54,150] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2022-03-04 13:26:54,154] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2022-03-04 13:26:54,158] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2022-03-04 13:26:58,151] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2022-03-04 13:26:58,161] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2022-03-04 13:26:59,044] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2022-03-04 13:26:59,049] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2022-03-04 13:26:59,161] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-04 13:28:57,108] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/car.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/car.jpg'
[2022-03-04 13:28:57,360] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2022-03-04 13:28:57,366] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7f8b3c0548b0>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8b3c0548b0>
[2022-03-04 13:30:18,313] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:163 - [Errno 2] No such file or directory: '/workspace/images/car.jpg'
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 160, in retrieve_source_fn
    async with async_open(file_key, 'rb') as afp:
  File "/usr/local/lib/python3.8/site-packages/aiofile/utils.py", line 179, in __aenter__
    await self.file.open()
  File "/usr/local/lib/python3.8/site-packages/aiofile/aio.py", line 152, in open
    self.__file_obj = await self._run_in_thread(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/images/car.jpg'
[2022-03-04 13:30:18,320] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:282 - Message processing failed, message NOT requeued
[2022-03-04 13:30:18,324] [ERROR] baseworker_controller /workspace/src/baseworker_controller.py:283 - cannot identify image file <_io.BytesIO object at 0x7f8b3c035d10>
Traceback (most recent call last):
  File "/workspace/src/baseworker_controller.py", line 178, in _handler_fn
    delegate_output_data = await self.handler.inference_handler(retrieve_source_fn, job_context, job_data, job_action)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 110, in inference_handler
    pil_img = pil_conversion(source_data)
  File "/workspace/src/message_handlers/objectV5_handler.py", line 82, in pil_conversion
    image = Image.open(stream).convert('RGB')
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8b3c035d10>
[2022-03-04 13:36:15,512] [WARNING] __main__ main.py:182 - closing all external connections
[2022-03-04 13:36:15,517] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2022-03-04 13:36:15,520] [WARNING] __main__ main.py:194 - asyncmain exiting
[2022-03-04 13:47:35,297] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2022-03-04 13:47:35,300] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2022-03-04 13:47:35,304] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2022-03-04 13:47:35,307] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2022-03-04 13:47:35,311] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2022-03-04 13:47:35,314] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2022-03-04 13:47:35,317] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2022-03-04 13:47:35,321] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2022-03-04 13:47:35,326] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2022-03-04 13:47:38,700] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2022-03-04 13:47:38,705] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2022-03-04 13:47:39,804] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2022-03-04 13:47:39,807] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2022-03-04 13:47:39,945] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-04 13:48:07,156] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2022-03-04 13:48:07,173] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2022-03-04 13:49:52,098] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2022-03-04 13:49:52,103] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2022-03-04 13:52:44,253] [WARNING] __main__ main.py:182 - closing all external connections
[2022-03-04 13:52:44,260] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2022-03-04 13:52:44,274] [WARNING] __main__ main.py:194 - asyncmain exiting
[2022-03-04 13:53:21,692] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2022-03-04 13:53:21,697] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2022-03-04 13:53:21,702] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2022-03-04 13:53:21,708] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2022-03-04 13:53:21,713] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2022-03-04 13:53:21,718] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2022-03-04 13:53:21,725] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2022-03-04 13:53:21,732] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2022-03-04 13:53:21,738] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2022-03-04 13:53:24,987] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2022-03-04 13:53:24,994] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2022-03-04 13:53:25,791] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2022-03-04 13:53:25,795] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2022-03-04 13:53:25,892] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-04 13:53:41,098] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2022-03-04 13:53:41,109] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2022-03-04 13:54:14,644] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2022-03-04 13:54:14,651] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2022-03-04 13:56:48,857] [WARNING] __main__ main.py:182 - closing all external connections
[2022-03-04 13:56:48,866] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2022-03-04 13:56:48,872] [WARNING] __main__ main.py:194 - asyncmain exiting
[2022-03-06 14:03:54,177] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2022-03-06 14:03:54,183] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2022-03-06 14:03:54,191] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2022-03-06 14:03:54,198] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2022-03-06 14:03:54,205] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2022-03-06 14:03:54,213] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2022-03-06 14:03:54,227] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2022-03-06 14:03:54,253] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2022-03-06 14:03:54,259] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2022-03-06 14:04:14,274] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2022-03-06 14:04:14,302] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2022-03-06 14:04:16,384] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2022-03-06 14:04:16,390] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2022-03-06 14:04:16,704] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-06 14:16:36,869] [WARNING] __main__ main.py:182 - closing all external connections
[2022-03-06 14:16:36,895] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2022-03-06 14:16:36,910] [WARNING] __main__ main.py:194 - asyncmain exiting
[2022-03-06 14:17:12,016] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2022-03-06 14:17:12,019] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2022-03-06 14:17:12,023] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2022-03-06 14:17:12,032] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2022-03-06 14:17:12,039] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2022-03-06 14:17:12,055] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2022-03-06 14:17:12,064] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2022-03-06 14:17:12,071] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2022-03-06 14:17:12,075] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2022-03-06 14:17:17,974] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2022-03-06 14:17:17,993] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2022-03-06 14:17:20,334] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2022-03-06 14:17:20,343] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2022-03-06 14:17:20,582] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-06 14:29:23,731] [WARNING] __main__ main.py:182 - closing all external connections
[2022-03-06 14:29:23,739] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2022-03-06 14:29:23,743] [WARNING] __main__ main.py:194 - asyncmain exiting
[2022-03-06 14:33:48,236] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2022-03-06 14:33:48,241] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2022-03-06 14:33:48,248] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2022-03-06 14:33:48,255] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2022-03-06 14:33:48,262] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2022-03-06 14:33:48,266] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2022-03-06 14:33:48,271] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2022-03-06 14:33:48,285] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2022-03-06 14:33:48,293] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2022-03-06 14:33:53,888] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2022-03-06 14:33:53,900] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2022-03-06 14:33:55,448] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2022-03-06 14:33:55,454] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2022-03-06 14:33:55,633] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-06 15:04:55,330] [WARNING] __main__ main.py:182 - closing all external connections
[2022-03-06 15:04:55,363] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2022-03-06 15:04:55,401] [WARNING] __main__ main.py:194 - asyncmain exiting
